apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: fintech-platform
data:
  url: "redis-master:6379"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: fintech-platform
data:
  brokers: "kafka-0.kafka-headless:9092,kafka-1.kafka-headless:9092,kafka-2.kafka-headless:9092"
